### ISSUE TITLE
Building with Xcode 26.4 fails with MatrixRustSDK compilation errors

### ISSUE THREAD

**Issue by hughns** [element-hq/element-x-ios#5321]
When trying to build using Xcode 26.4 (using the published SDK) the build fails with:

```
/Users/user/Library/Developer/Xcode/DerivedData/ElementX-eamgntshwtxkljbzmfuoymtkolyg/SourcePackages/checkouts/matrix-rust-components-swift/Sources/MatrixRustSDK/matrix_sdk_base.swift:14:23: error: cannot find type 'RustBuffer' in scope
fileprivate extension RustBuffer {
                      ^~~~~~~~~~
```

In the issue pane it looks like this:

<img width="824" height="880" alt="Image" src="https://github.com/user-attachments/assets/d559bb84-17bb-478e-b8d2-ab3630389d12" />

This is possibly the same issue as https://github.com/matrix-org/matrix-rust-components-swift/issues/32 but creating a tracker in the element-x-ios repo for better visibility.

The workaround is to use Xcode 26.3 for now.
